apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kgnj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lbxl-tenant/rhtap-demo-app/hacbs-test-project-kgnj@sha256:1d25f660df5b2eec407ec8cb0bc6d35825d24e3f10bf6448ac9f8e76aaa79a3b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
