apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-kgnj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lbxl-tenant/rhtap-demo-app/hacbs-test-project-kgnj@sha256:a8ad9dfe71871857113bbce7542d099c729d1541289d9e4714ae273416591af5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
