apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kgnj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kgnj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kgnj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kgnj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kgnj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lbxl-tenant/rhtap-demo-app/hacbs-test-project-kgnj@sha256:a8ad9dfe71871857113bbce7542d099c729d1541289d9e4714ae273416591af5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
